"use client";
import React from "react";

export default function PrivacyPolicy() {
  return (
    <main className="relative p-6 md:p-12">
      <div className="max-w-screen-2xl mx-auto shadow-md rounded-2xl">
        <header className="flex items-start justify-between p-6 border-b">
          <div>
            <br />
            <h1 className="text-2xl md:text-3xl font-semibold text-[#c69b48]">
              Privacy Policy
            </h1>
            <p className="text-sm mt-1">
              Updated at December 1st, 2025
            </p>
          </div>
        </header>

        <div className="md:flex">
          <article className="flex-1 p-6 prose prose-sm max-w-none">
            
            {/* Introduction */}
            <section id="intro">
              <p className="text-sm">
                Consultants R Us (“we,” “our,” or “us”) is committed to
                protecting your privacy. This Privacy Policy explains how your
                personal information is collected, used, and disclosed by
                Consultants R Us.
              </p>
              <p className="text-sm">
                This Privacy Policy applies to our app, and its associated
                subdomains (collectively, our “Service”) alongside our
                application, Consultants R Us. By accessing or using our
                Service, you signify that you have read, understood, and agree
                to our collection, storage, use, and disclosure of your
                personal information as described in this Privacy Policy and
                our Terms of Service.
              </p>
            </section>

            {/* Definitions */}
            <section id="definitions">
              <br />
              <h2 className="text-[#c69b48]">Definitions and Key Terms</h2>
              <p className="text-sm">
                To help explain things as clearly as possible in this Privacy
                Policy, every time any of these terms are referenced, they are
                strictly defined as:
              </p>
              <ul className="list-disc ml-6 text-sm">
                <li><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Consultants R Us Inc, (1267 CR 220L Denver City, TX), that is responsible for your information under this Privacy Policy.</li>
                <li><strong>Country:</strong> where Consultants R Us or the owners/founders of Consultants R Us are based, in this case is United States</li>
                <li><strong>Customer:</strong> refers to the company, organization or person that signs up to use the Consultants R Us Service to manage the relationships with your consumers or service users.</li>
                <li><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Consultants R Us and use the services.</li>
                <li><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li><strong>Personnel:</strong> refers to those individuals who are employed by Consultants R Us or are under contract to perform a service on behalf of one of the parties.</li>
                <li><strong>Personal Data:</strong> any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                <li><strong>Service:</strong> refers to the service provided by Consultants R Us as described in the relative terms (if available) and on this platform.</li>
                <li><strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li><strong>App/Application:</strong> Consultants R Us app, refers to the SOFTWARE PRODUCT identified above.</li>
                <li><strong>You:</strong> a person or entity that is registered with Consultants R Us to use the Services.</li>
              </ul>
            </section>

            {/* Information Collection */}
            <section id="info-collection">
              <br />
              <h2 className="text-[#c69b48]">What Information Do We Collect?</h2>
              <p className="text-sm">
                We collect information from you when you visit our app, register, place an order, subscribe, respond to a survey or fill out a form:
              </p>
              <ul className="list-disc ml-6 text-sm">
                <li>Name / Username</li>
                <li>Phone Numbers</li>
                <li>Email Addresses</li>
                <li>Job Titles</li>
                <li>Debit/credit card numbers</li>
                <li>Age</li>
                <li>Password</li>
              </ul>
              <p className="text-sm">
                We also collect information from mobile devices for a better user experience, although these features are completely optional:
              </p>
              <ul className="list-disc ml-6 text-sm">
                <li><strong>Camera (Pictures):</strong> Granting camera permission allows the user to upload any picture straight from the platform, you can safely deny camera permissions for this platform.</li>
                <li><strong>Photo Gallery (Pictures):</strong> Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this platform.</li>
              </ul>
            </section>

            {/* Third-party info */}
            <section id="third-party-info">
              <br />
              <h2 className="text-[#c69b48]">When does Consultants R Us use end user / customer information from third parties?</h2>
              <p className="text-sm"><strong>End Users:</strong> Consultants R Us will collect End User Data necessary to provide the Consultants R Us services to our customers. End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>
              <p className="text-sm"><strong>Customers:</strong> We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Consultants R Us customer, we receive information from a third party that provides automated fraud detection services to Consultants R Us. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</p>
            </section>

            {/* Sharing */}
            <section id="sharing-info">
              <br />
              <h2 className="text-[#c69b48]">Do We Share The Information We Collect With Third Parties?</h2>
              <p className="text-sm">We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.</p>
              <p className="text-sm">We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the app, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the app. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.</p>
              <p className="text-sm">We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the app in a shared location, and type of the device used to visit the app. They may aggregate information about our advertising and what you see on the app and then provide auditing, research and reporting for us and our advertisers.</p>
              <p className="text-sm">We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.</p>
            </section>

            {/* Data Usage */}
            <section id="data-usage">
              <br />
              <h2 className="text-[#c69b48]">How Do We Use The Information We Collect?</h2>
              <p className="text-sm">Any of the information we collect from you may be used in one of the following ways:</p>
              <ul className="list-disc ml-6 text-sm">
                <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
                <li>To improve our app (we continually strive to improve our app offerings based on the information and feedback we receive from you)</li>
                <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
                <li>To process transactions</li>
                <li>To administer a contest, promotion, survey or other site feature</li>
                <li>To send periodic emails</li>
              </ul>
            </section>

            {/* Email Usage */}
            <section id="email-usage">
              <br />
              <h2 className="text-[#c69b48]">How Do We Use Your Email Address?</h2>
              <p className="text-sm">By submitting your email address on this app, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</p>
            </section>

            {/* Cookies */}
            <section id="cookies">
              <br />
              <h2 className="text-[#c69b48]">Cookies</h2>
              <p className="text-sm">Consultants R Us uses "Cookies" to identify the areas of our app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the app as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our app correctly or at all. We never place Personally Identifiable Information in Cookies.</p>
            </section>

            {/* Blocking Cookies */}
            <section id="blocking-cookies">
              <br />
              <h2 className="text-[#c69b48]">Blocking and disabling cookies and similar technologies</h2>
              <p className="text-sm">Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our app from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.</p>
            </section>

            {/* Tracking Technologies */}
            <section id="tracking">
              <br />
              <h2 className="text-[#c69b48]">Tracking Technologies</h2>
              <ul className="list-disc ml-6 text-sm">
                <li><strong>Local Storage</strong> – Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.</li>
                <li><strong>Sessions</strong> – We use "Sessions" to identify the areas of our platform that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.</li>
              </ul>
            </section>

            {/* Payment Details */}
            <section id="payment">
              <br />
              <h2 className="text-[#c69b48]">Payment Details</h2>
              <p className="text-sm">In respect to any credit card or other payment processing details you have provided us, we commit that this confidential information will be stored in the most secure manner possible.</p>
            </section>

            {/* Kids' Privacy */}
            <section id="kids">
              <br />
              <h2 className="text-[#c69b48]">Kids' Privacy</h2>
              <p className="text-sm">We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
            </section>

            {/* Data Retention */}
            <section id="data-retention">
              <br />
              <h2 className="text-[#c69b48]">How Long Do We Keep Your Information?</h2>
              <p className="text-sm">We keep your information only so long as we need it to provide Consultants R Us to you and fulfill the purposes described in this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.</p>
            </section>

            {/* Data Protection */}
            <section id="data-protection">
              <br />
              <h2 className="text-[#c69b48]">How Do We Protect Your Information?</h2>
              <p className="text-sm">We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Consultants R Us or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.</p>
            </section>

            {/* International Transfer */}
            <section id="international-transfer">
              <br />
              <h2 className="text-[#c69b48]">Could My Information Be Transferred To Other Countries?</h2>
              <p className="text-sm">Consultants R Us is incorporated in United States. Information collected via our app, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.</p>
            </section>

            {/* Links to Other Websites */}
            <section id="links">
              <br />
              <h2 className="text-[#c69b48]">Links to Other Websites</h2>
              <p className="text-sm">This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by Consultants R Us. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</p>
            </section>

            {/* Sale of Business */}
            <section id="sale">
              <br />
              <h2 className="text-[#c69b48]">Sale of Business</h2>
              <p className="text-sm">We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of Consultants R Us or any of its Corporate Affiliates (as defined herein), or that portion of Consultants R Us or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.</p>
            </section>

            {/* Affiliates */}
            <section id="affiliates">
              <br />
              <h2 className="text-[#c69b48]">Affiliates</h2>
              <p className="text-sm">We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with Consultants R Us, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.</p>
            </section>

            {/* Governing Law */}
            <section id="governing-law">
              <br />
              <h2 className="text-[#c69b48]">Governing Law</h2>
              <p className="text-sm">This Privacy Policy is governed by the laws of United States without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.</p>
              <p className="text-sm">The laws of United States, excluding its conflicts of law rules, shall govern this Agreement and your use of the app. Your use of the app may also be subject to other local, state, national, or international laws.</p>
              <p className="text-sm">By using Consultants R Us or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our app, or use our services. Continued use of the app, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.</p>
            </section>

            {/* Changes to Policy */}
            <section id="changes">
              <br />
              <h2 className="text-[#c69b48]">Changes To Our Privacy Policy</h2>
              <p className="text-sm">We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.</p>
            </section>

            {/* GDPR */}
            <section id="gdpr">
              <br />
              <h2 className="text-[#c69b48]">Information about General Data Protection Regulation (GDPR)</h2>
              <p className="text-sm">We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under protection from being replicated or used in the wrong way.</p>
              <p className="text-sm">GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and enhances the control the EU residents have, over their personal data.</p>
              <p className="text-sm">The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our customers’ data is important irrespective of where they are located, which is why we have implemented GDPR controls as our baseline standard for all our operations worldwide.</p>
              <p className="text-sm">We are committed to helping our customers meet the data subject rights requirements of GDPR. Consultants R Us processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.</p>
            </section>

            {/* California Residents */}
            <section id="california">
              <br />
              <h2 className="text-[#c69b48]">California Residents</h2>
              <p className="text-sm">The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.</p>
              <p className="text-sm">We are also required to communicate information about rights California residents have under California law. You may exercise the following rights: Right to Know and Access, Right to Equal Service, Right to Delete, and Right to request that a business that sells a consumer's personal data, not sell the consumer's personal data.</p>
              <p className="text-sm">We do not sell the Personal Information of our users. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>
              <p className="text-sm">CalOPPA users have the same rights as listed above.</p>
            </section>

            {/* Consent */}
            <section id="consent">
              <br />
              <h2 className="text-[#c69b48]">Your Consent</h2>
              <p className="text-sm">We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our Consultants R Us, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.</p>
            </section>

            {/* Contact */}
            <section id="contact">
              <br />
              <h2 className="text-[#c69b48]">Contact Us</h2>
              <p className="text-sm">Don't hesitate to contact us if you have any questions.</p>
              <ul className="list-disc ml-6 text-sm">
                <li>Email: <a href="mailto:info@Consultantsrus.com" className="text-blue-600 underline">info@Consultantsrus.com</a></li>
                <li>Phone: +1 806 215 6795</li>
                <li>Website: <a href="https://www.consultantsrus.co/" target="_blank" rel="noopener noreferrer" className="text-blue-600 underline">https://www.consultantsrus.co/</a></li>
                <li>Address: 1267 CR 220L Denver City, TX</li>
              </ul>
            </section>

          </article>
        </div>
      </div>
    </main>
  );
}